# Dockerfile.test

# Use a base Python image
FROM python:3.9-slim

# Install system dependencies needed for 'blis'
# This includes gcc, a C compiler, which is required to build the C-extensions
# used by blis and other packages like spacy.
RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    tesseract-ocr \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app


# Install the dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application source code
#COPY src src
#COPY scripts scripts
# Assuming your Dockerfile.test is in the project root
# and you're copying all files into the /app directory in the container
COPY . /app
COPY .env .

# You can define an entrypoint here, but the docker-compose command is enough



