# FROM python:3.9-slim
# RUN apt-get update && apt-get install -y gcc build-essential
# WORKDIR /app
# COPY requirements.txt .
# RUN pip install -r requirements.txt
# COPY . .
# CMD uvicorn src.main:app --host 0.0.0.0 --port 8080


FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN apt-get update && apt-get install -y gcc build-essential tesseract-ocr \
 && pip install --no-cache-dir -r requirements.txt \
 && apt-get purge -y gcc build-essential && apt-get autoremove -y \
 && rm -rf /var/lib/apt/lists/*
COPY . .
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]
