#src/processing/embedding/base.py
from abc import ABC, abstractmethod
from typing import List
from src.config import settings


class EmbeddingGenerator(ABC):
    """Abstract base class for embedding generators."""

    @abstractmethod
    def generate_embedding(self, text: str) -> List[float]:
        """Generate embedding for a single text string."""
        pass

    @abstractmethod
    def generate_embeddings_batch(self, texts: List[str]) -> List[List[float]]:
        """Generate embeddings for a batch of text strings."""
        pass

    @abstractmethod
    def get_embedding_dimension(self) -> int:
        """Get the dimension of the embeddings generated by this model."""
        pass


class EmbeddingGeneratorFactory:
    """Factory class to create embedding generators based on configuration."""

    @staticmethod
    def create_embedding_generator() -> EmbeddingGenerator:
        """Create an embedding generator based on the configuration."""
        if settings.embedding_type == "vertex_ai":
            from .vertex_ai import VertexAIEmbeddingGenerator
            return VertexAIEmbeddingGenerator()
        else:  # Default to local
            from .local import LocalEmbeddingGenerator
            return LocalEmbeddingGenerator()
